### ISSUE TITLE
Improve Description for Additional Tabs

### ISSUE THREAD

**Issue by kristineds** [websharks/wp-site-search#4]
In the **Additional Tabs** section, it would be nice if we could improve the description, explain what the syntax represents and how it works . The provided example is not clear enough. e.g., `Title`|`pattern` ... _(one per line)_.  

![screen shot 2016-09-17 at 12 01 27 am](https://cloud.githubusercontent.com/assets/7514953/18592621/647c6e5a-7c6a-11e6-8a27-da1493822509.png)

------------------

From [convo with @jaswsinc:](https://websharks.slack.com/archives/wp-site-search/p1474004561000010)

>  A KB article can help to explain this.

**Comment by jaswsinc** [comment]
This takes the form of `Title`|`pattern` and that means that you type the Title of the Tab that will be shown to users when they are searching your site, and then the search pattern that narrows the results in some way whenever that tab is clicked.

The search pattern is extremely powerful, because you're searching the ENTIRE web. So for instance, here is a list of tabs that filters the web in slightly different ways.

```
Products @ WP Sharks|wpsharks.com/product/*
KB Articles @ WP Sharks|wpsharks.com/kb-article/*
Product-Specific KBAs @ WP Sharks|wpsharks.com/kb-article/wp-site-search-pro/*
CNET News|www.cnet.com/news/*
Comet Cache|cometcache.com/*
s2Member|s2member.com/*
```

**Comment by jaswsinc** [comment]
https://wpsharks.com/kb-article/wp-site-search-pro/creating-custom-search-tabs
